/*
 * Copyright 2012 TennenColl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// From http://forum.sa-mp.com/showthread.php?t=152174

#ifndef FRESHCITY_APPLICATION_GAMEMODE_DEFINITION_COLOR
#define FRESHCITY_APPLICATION_GAMEMODE_DEFINITION_COLOR

//Shades of red
const int COLOR_INDIANRED = 0xCD5C5CFF;
const int COLOR_LIGHTCORAL = 0xF08080FF;
const int COLOR_SALMON = 0xFA8072FF;
const int COLOR_DARKSALMON = 0xE9967AFF;
const int COLOR_LIGHTSALMON = 0xFFA07AFF;
const int COLOR_CRIMSON = 0xDC143CFF;
const int COLOR_RED = 0xFF0000FF;
const int COLOR_FIREBRICK = 0xB22222FF;
const int COLOR_DARKRED = 0x8B0000FF;

//Shades of pink
const int COLOR_PINK = 0xFFC0CBFF;
const int COLOR_LIGHTPINK = 0xFFB6C1FF;
const int COLOR_HOTPINK = 0xFF69B4FF;
const int COLOR_DEEPPINK = 0xFF1493FF;
const int COLOR_MEDIUMVIOLETRED = 0xC71585FF;
const int COLOR_PALEVIOLETRED = 0xDB7093FF;

//Shades of Orange
const int COLOR_CORAL = 0xFF7F50FF;
const int COLOR_TOMATO = 0xFF6347FF;
const int COLOR_ORANGERED = 0xFF4500FF;
const int COLOR_DARKORANGE = 0xFF8C00FF;
const int COLOR_ORANGE = 0xFFA500FF;

//Shades of Yellow
const int COLOR_GOLD = 0xFFD700FF;
const int COLOR_YELLOW = 0xFFFF00FF;
const int COLOR_LIGHTYELLOW = 0xFFFFE0FF;
const int COLOR_LEMONCHIFFON = 0xFFFACDFF;
const int COLOR_LIGHTGOLDENRODYELLOW = 0xFAFAD2FF;
const int COLOR_PAPAYAWHIP = 0xFFEFD5FF;
const int COLOR_MOCCASIN = 0xFFE4B5FF;
const int COLOR_PEACHPUFF = 0xFFDAB9FF;
const int COLOR_PALEGOLDENROD = 0xEEE8AAFF;
const int COLOR_KHAKI = 0xF0E68CFF;
const int COLOR_DARKKHAKI = 0xBDB76BFF;

//Shades of Purple
const int COLOR_LAVENDER = 0xE6E6FAFF;
const int COLOR_THISTLE = 0xD8BFD8FF;
const int COLOR_PLUM = 0xDDA0DDFF;
const int COLOR_VIOLET = 0xEE82EEFF;
const int COLOR_ORCHID = 0xDA70D6FF;
const int COLOR_FUCHSIA = 0xFF00FFFF;
const int COLOR_MAGENTA = 0xFF00FFFF;
const int COLOR_MEDIUMORCHID = 0xBA55D3FF;
const int COLOR_MEDIUMPURPLE = 0x9370DBFF;
const int COLOR_AMETHYST = 0x9966CCFF;
const int COLOR_BLUEVIOLET = 0x8A2BE2FF;
const int COLOR_DARKVIOLET = 0x9400D3FF;
const int COLOR_DARKORCHID = 0x9932CCFF;
const int COLOR_DARKMAGENTA = 0x8B008BFF;
const int COLOR_PURPLE = 0x800080FF;
const int COLOR_INDIGO = 0x4B0082FF;
const int COLOR_SLATEBLUE = 0x6A5ACDFF;
const int COLOR_DARKSLATEBLUE = 0x483D8BFF;

//Shades of Green
const int COLOR_GREENYELLOW = 0xADFF2FFF;
const int COLOR_CHARTREUSE = 0x7FFF00FF;
const int COLOR_LAWNGREEN = 0x7CFC00FF;
const int COLOR_LIME = 0x00FF00FF;
const int COLOR_LIMEGREEN = 0x32CD32FF;
const int COLOR_PALEGREEN = 0x98FB98FF;
const int COLOR_LIGHTGREEN = 0x90EE90FF;
const int COLOR_MEDIUMSPRINGGREEN = 0x00FA9AFF;
const int COLOR_SPRINGGREEN = 0x00FF7FFF;
const int COLOR_MEDIUMSEAGREEN = 0x3CB371FF;
const int COLOR_SEAGREEN = 0x2E8B57FF;
const int COLOR_FORESTGREEN = 0x228B22FF;
const int COLOR_GREEN = 0x008000FF;
const int COLOR_DARKGREEN = 0x006400FF;
const int COLOR_YELLOWGREEN = 0x9ACD32FF;
const int COLOR_OLIVEDRAB = 0x6B8E23FF;
const int COLOR_OLIVE = 0x808000FF;
const int COLOR_DARKOLIVEGREEN = 0x556B2FFF;
const int COLOR_MEDIUMAQUAMARINE = 0x66CDAAFF;
const int COLOR_DARKSEAGREEN = 0x8FBC8FFF;
const int COLOR_LIGHTSEAGREEN = 0x20B2AAFF;
const int COLOR_DARKCYAN = 0x008B8BFF;
const int COLOR_TEAL = 0x008080FF;

//Shades of Blue/Cyan
const int COLOR_AQUA = 0x00FFFFFF;
const int COLOR_CYAN = 0x00FFFFFF;
const int COLOR_LIGHTCYAN = 0xE0FFFFFF;
const int COLOR_PALETURQUOISE = 0xAFEEEEFF;
const int COLOR_AQUAMARINE = 0x7FFFD4FF;
const int COLOR_TURQUOISE = 0x40E0D0FF;
const int COLOR_MEDIUMTURQUOISE = 0x48D1CCFF;
const int COLOR_DARKTURQUOISE = 0x00CED1FF;
const int COLOR_CADETBLUE = 0x5F9EA0FF;
const int COLOR_STEELBLUE = 0x4682B4FF;
const int COLOR_LIGHTSTEELBLUE = 0xB0C4DEFF;
const int COLOR_POWDERBLUE = 0xB0E0E6FF;
const int COLOR_LIGHTBLUE = 0xADD8E6FF;
const int COLOR_SKYBLUE = 0x87CEEBFF;
const int COLOR_LIGHTSKYBLUE = 0x87CEFAFF;
const int COLOR_DEEPSKYBLUE = 0x00BFFFFF;
const int COLOR_DODGERBLUE = 0x1E90FFFF;
const int COLOR_CORNFLOWERBLUE = 0x6495EDFF;
const int COLOR_MEDIUMSLATEBLUE = 0x7B68EEFF;
const int COLOR_ROYALBLUE = 0x4169E1FF;
const int COLOR_BLUE = 0x0000FFFF;
const int COLOR_MEDIUMBLUE = 0x0000CDFF;
const int DARKBLUE = 0x00008BFF;
const int COLOR_NAVY = 0x000080FF;
const int COLOR_MIDNIGHTBLUE = 0x191970FF;

//Shades of Brown
const int COLOR_CORNSILK = 0xFFF8DCFF;
const int COLOR_BLANCHEDALMOND = 0xFFEBCDFF;
const int COLOR_BISQUE = 0xFFE4C4FF;
const int COLOR_NAVAJOWHITE = 0xFFDEADFF;
const int COLOR_WHEAT = 0xF5DEB3FF;
const int COLOR_BURLYWOOD = 0xDEB887FF;
const int COLOR_TAN = 0xD2B48CFF;
const int COLOR_ROSYBROWN = 0xBC8F8FFF;
const int COLOR_SANDYBROWN = 0xF4A460FF;
const int COLOR_DARKGOLDENROD = 0xB8860BFF;
const int COLOR_PERU = 0xCD853FFF;
const int COLOR_SADDLEBROWN = 0x8B4513FF;
const int COLOR_SIENNA = 0xA0522DFF;
const int COLOR_BROWN = 0xA52A2AFF;
const int COLOR_MAROON = 0x800000FF;

//Shades of Grey
const int COLOR_WHITE = 0xFFFFFFFF;
const int COLOR_GAINSBORO = 0xDCDCDCFF;
const int COLOR_LIGHTGREY = 0xD3D3D3FF;
const int COLOR_SILVER = 0xC0C0C0FF;
const int COLOR_DARKGRAY = 0xA9A9A9FF;
const int COLOR_GRAY = 0x808080FF;
const int COLOR_DIMGRAY = 0x696969FF;
const int COLOR_LIGHTSLATEGRAY = 0x778899FF;
const int COLOR_SLATEGRAY = 0x708090FF;
const int COLOR_DARKSLATEGRAY = 0x2F4F4FFF;
const int COLOR_BLACK = 0x000000FF;

#define COLOR_INFO COLOR_WHITE
#define COLOR_WARN COLOR_WHEAT
#define COLOR_ERROR COLOR_ORANGE
#define COLOR_SUCC COLOR_AQUA

#endif
